### ISSUE TITLE
Add time series for selected regions

### ISSUE THREAD

**Issue by tobstac** [semohr/risikogebiete_deutschland#10]
Thanks a lot for this very nice overview! This is data well presented!

Would it be possible to also add time series? Maybe not as overlay like you do with the incidence data because then the plot might become too crowded. But a feature like: click on a region and get a popup window that displays the time series of incidence for the age classes in the respective region would be great.

This might be a nice way to visualize the effect of certain measures (vaccination, closing/opening schools, or curfews) on the respective age class.

**Comment by semohr** [comment]
Sadly it is not easily doable as website (at least in my highcharts framework) but you can have a look [here](https://github.com/Priesemann-Group/covid19_research/tree/master/incidence_landkreise). I have done basically what you are asking for with matplotlib.

**Comment by tobstac** [comment]
That's a pity, but thanks for the link - this also looks very interesting!

**Comment by magocpp** [comment]
A simpler option could be a global dropdown menu to select a specific dataset (latest default selected)

**Comment by semohr** [comment]
There is a time slider now on the website! Have a look if you haven't done so already ;)
