### ISSUE TITLE
New display problem on mobile devices

### ISSUE THREAD

**Issue by ScientiaFacultas** [semohr/risikogebiete_deutschland#11]
Regarding mobile devices (Android: Chrome and Samsung browsers):

Since the update to the text regarding the change in population numbers, the gray bounding box for the age groups covers the entire map so that it is not possible to select individual counties (SK/LK).

Thanks for this great tool!!

**Comment by semohr** [comment]
Can't reproduce the problem with my devices :/ Maybe someone wants to help with that, the problem is most likely from `width:min-content` css styling.

**Comment by HenningLanghorst** [comment]
I can reproduce it on my iPad (iPadOS 14.4.2): https://drive.google.com/file/d/19hkOTxceCS1_ea-zI7KfspMY_8Itkv7p/view?usp=drivesdk

**Comment by ScientiaFacultas** [comment]
Now it works again on my devices!
