### ISSUE TITLE
Integration into covid-ampel

### ISSUE THREAD

**Issue by stritti** [semohr/risikogebiete_deutschland#14]
Hi @semohr 

really great map of the incidences! What do you think, I would like to integrate it into my project: https://covid-ampel.vercel.app (Repository: https://github.com/stritti/covid-ampel-widget)

**Comment by semohr** [comment]
Hi stritti,

Thank you for the kind words and your interest in my work. I don't mind if you use my data and code. If you just want to use the data and do your own visualization you can find it [here](https://github.com/semohr/risikogebiete_deutschland/tree/master/assets/data). The plotting routines [(see here)](https://github.com/semohr/risikogebiete_deutschland/blob/master/assets/js/main.js) may be a bit messy, but should be understandable with a look into the highcharts documentation [here](https://api.highcharts.com/highmaps/).

Good luck with your project and feel free to quote me if you decide to use something from my repo.

Best, Sebastian

**Comment by stritti** [comment]
Hi Sebastian,

many thanks for your support. I added the map just by using an iframe: https://github.com/stritti/covid-ampel-widget/pull/67 

Grüße Stephan
