### ISSUE TITLE
Adjust color scale to make it easier to perceive the data

### ISSUE THREAD

**Issue by Wosi** [semohr/risikogebiete_deutschland#2]
First of all: Thank you very much for making this project. It is very helpful!

I think the color scale makes it hard to differntiate incidence values above 50. Compare these two charts from https://semohr.github.io/risikogebiete_deutschland/ and  https://www.risklayer-explorer.com/event/100/detail which show (almost) the same data:
![grafik](https://user-images.githubusercontent.com/3448684/114721734-80879d00-9d39-11eb-9e6f-f225be40d584.png)
![grafik](https://user-images.githubusercontent.com/3448684/114721800-91d0a980-9d39-11eb-9e26-afa649cd2d7f.png)

I think it would help to use a similar color scale on this site as well.
Keep up the good work!

**Comment by semohr** [comment]
Thank you for your input. I change the colour of the high incidence groups to match the risklayer scheme. I still see a problem for people with green-red colour blindness on both visualisations thought.
