### ISSUE TITLE
Data for LK Ludwigslust-Parchim not reported

### ISSUE THREAD

**Issue by felix-schwarz** [semohr/risikogebiete_deutschland#22]
There seems to be no data reported for LK Ludwigslust-Parchim (or, more precise: only 0 cases). The RKI Dashboard shows numbers for it, so there seems to be an error.

Also, THANKS for making this map!

**Comment by semohr** [comment]
Hi Felix,

For me the data is also not show on the [RKI dashboard](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_1/). Could you add a link to your source?
![Screenshot_20211102-121212_Chrome.png](https://user-images.githubusercontent.com/39738318/139836452-a63ac079-ebdf-4754-b81b-dca1b63e622e.png)

Best, Sebastian

**Comment by felix-schwarz** [comment]
You're right! I confused it with the Risklayer map, which has data (sourcing it from https://www.kreis-lup.de ). Wondering why RKI has none.

Anyways, _that_ issue is certainly outside the scope of this project and I'm closing the issue. Sorry!

**Comment by mowny** [comment]
Shouldn't the LK be drawn as white, then, just like Eisenach?

**Comment by semohr** [comment]
Yes you are right, it should be gray. I will try to fix that. I would also be happy to incorporate the data from [https://www.kreis-lup.de](https://www.kreis-lup.de) but they do not publish age resolved case numbers.

Best, Sebastian
