### ISSUE TITLE
Eisenach ist kein eigener Kreis mehr

### ISSUE THREAD

**Issue by belzebub40k** [semohr/risikogebiete_deutschland#23]
Das Problem wurde schon in #21 angesprochen. Nachdem ich diesen Fleck auf der Karte des RKI COVID-19-Dashboard aber nicht sehen konnte habe ich mal etwas nachgeforscht und es ist wohl so das Eisenach seit dem 1. Juli 2021 keine kreisfreie Stadt mehr ist sondern zum Wartburgkreis gehört.

https://de.wikipedia.org/wiki/Eisenach
> Eisenach ist eine Stadt im Wartburgkreis... Die Mittelstadt war von 1998 bis zum 30. Juni 2021 kreisfreie Stadt...

**Comment by semohr** [comment]
Wow danke für die Info. Darauf hätte man auch kommen können. Sollte einfach zu beheben sein indem man die geojson Datei aktualisiert. 

Schaue ich mir die Tage mal an!

LG, Sebastian
