### ISSUE TITLE
Adjustable custom age group parameters

### ISSUE THREAD

**Issue by paugre** [semohr/risikogebiete_deutschland#24]
Thank you for this handy map. 

It would be great to have the option to filter shown incidence rates by custom age ranges, such as for example 6-12 years to capture largely unvaccinated school age populations. 

It would be great to have the option to define custom age groups.

**Comment by semohr** [comment]
Please have a look into closed issues before you open a new one
Duplicate of #5 

There is no way to implement the requested feature!

**Comment by semohr** [comment]
Also duplicate of #15
