### ISSUE TITLE
Request: Other color range

### ISSUE THREAD

**Issue by Herbstfreud** [semohr/risikogebiete_deutschland#25]
Currently the color scheme begins with green, after this yellow, orange red - and then blue and violet are following. I think it would be better to have green and red (or dark red / brown / black?) on the opposing sides of the scale with more vellow and orange nuances in between.

We got used to traffic light colors over the years, so blue and violet don't really fit into this and also imply that there is no real danger.

**Comment by semohr** [comment]
Overall I'm not against changing colors, in fact we just changed colors to a more colorblind friendly schema (see #27). I feel like colors should not imply danger or in fact any other feeling. They should just be a way to visualize data, as I do not try to convey a political message.
