### ISSUE TITLE
history of data_latest.csv

### ISSUE THREAD

**Issue by JonathanN1203** [semohr/risikogebiete_deutschland#26]
Hi, 

is it possible to get a history of this file? https://github.com/semohr/risikogebiete_deutschland/blob/master/assets/data/data_latest.csv

**Comment by semohr** [comment]
Hi,
yes is possible. I created a [script](https://github.com/Priesemann-Group/covid19_research/blob/master/incidence_landkreise/time_series.py) at some point to write json files for each day. Maybe that is of use to you.
Best, Sebastian

**Comment by semohr** [comment]
Update: You can also download the [hdf5](https://github.com/semohr/risikogebiete_deutschland/blob/master/assets/data/timeseries_nd.hdf5) file or run the[ timeseries_data.py](https://github.com/semohr/risikogebiete_deutschland/blob/master/assets/python/timeseries_data.py) script now to obtain the timeseries/historic data.
