### ISSUE TITLE
Neue Farben?

### ISSUE THREAD

**Issue by bodhase** [semohr/risikogebiete_deutschland#28]
Schade, nimmt der ganzen schrecklichen Entwicklung jetzt die Dramatik. Durch die neue Farbgebung verliert die schwarze Welle von Südost nach Nordwest ihren Ausdruck. Man könnte fast meinen, Corona ist nun auf dem Rückzug. Jedenfalls auf den ersten Blick. Alles über 500 ist schlimm und gehört schwarz.
Danke für die gute Arbeit!

**Comment by semohr** [comment]
Meiner Meinung nach soll die Website nur Informationen darstellen. Dem entsprechend ist eine Farbwahl die es Menschen mit Achromatopsie ebenso ermöglicht die Website zu benutzten lange überfällig. 

Eventuell kann man aber wieder schwarz für die letzte Gruppe einführen, müsste ich mal ausprobieren.

(see also #25)

LG, Sebastian

**Comment by semohr** [comment]
FYI: Just implemented a checkbox on the website which allows you to change to the old color map.

**Comment by bodhase** [comment]
Perfekt!
