### ISSUE TITLE
Add functionality to zoom into a single Bundesland

### ISSUE THREAD

**Issue by valkum** [semohr/risikogebiete_deutschland#3]
Would it be possible to add a feature to zoom into a single Bundesland? Some smaller Kreise in NRW are really hard to hit with the mouse, especially on smaller displays.

How much work would that be?

**Comment by semohr** [comment]
I will see what I can do.
I'm not sure how to approach that yet maybe it is doable with css only than it would be an easy addition otherwise it may take a bit longer.

**Comment by valkum** [comment]
Maybe max and minZoomlevel? I am not familiar with the used js library. But it seems you set `map.maxZoomLevel = 1;`

**Comment by mgoellnitz** [comment]
I tried AGS-filtering the geo_json for a two-digit prefix, but failed with subsequent map scaling so far.

**Comment by valkum** [comment]
Thanks. Works for me at least on Desktop. I have not tried if this fix works flawless on mobile. But I don't believe such a map would be nice to view on mobile anyway.
