### ISSUE TITLE
incident color range should be a constant 

### ISSUE THREAD

**Issue by fmt-Println-MKO** [semohr/risikogebiete_deutschland#30]
With the latest version, the incident range of > 3000 was removed. 
Instead, the range from 2000 till 3000 got the black color.

This is confusing as you use the colors to understand what's happening. 

maybe you can also add a timestep, that you can go back day by day to visualize how it changed over time.

thank you :)

**Comment by semohr** [comment]
Was not my intention to change the colorscale. Happened on accident.
Best, Sebastian

**Comment by fmt-Println-MKO** [comment]
👍
