### ISSUE TITLE
Schick wäre eine weitere Aufgliederung zwischen 15 und 34

### ISSUE THREAD

**Issue by Wikinaut** [semohr/risikogebiete_deutschland#5]
see https://twitter.com/thinkslowly/status/1383346124392525827?s=20

**Comment by mgoellnitz** [comment]
Absolutely true, but a bit out of scope for an RKI data visualisation. RKI doesn't provide these other ages classes, thus there's no way of showing them here.

**Comment by semohr** [comment]
Sadly true. You could write to the RKI and ask them to supply the data but don't get your hopes up. -> Not available due to privacy reasons.

**Comment by taslior** [comment]
Would it be possible to get the data from survstat.rki.de As described here: https://twitter.com/Florian83616025/status/1380954278672613378?s=20 ?
I see tons of heatmaps on twitter with data from "RKI" or risklayer which has ages grouped by 5 years, for example here: https://coronavis.dbvis.de/de/overview/dashboard/38a3b6418ada1fd3600fc8c784d7b08a

Additionally if you want to panic even more :-(, the incidence could be normalized against the not vaccinated persons per county (the vaxxed ones do not get infected anymore hopefully). So far I haven't seen any numbers of vaxxed people by county (only by state), but these should be available as they are announced in the press.

**Comment by semohr** [comment]
Sadly this dataset is only updated once a week. Since I'm updating this website as soon as there is new data is not really usable for my use case.
