### ISSUE TITLE
Altersgruppen

### ISSUE THREAD

**Issue by streamsolutions** [semohr/risikogebiete_deutschland#9]
Hi 

i really like your project but you might want to check assigning the "altersgruppen" in

risikogebiete_deutschland/assets/python/update_data.py 

ie. showing A00-A04  which in reallity stands for    ["unter 3 Jahre"] +["3 bis unter 6 Jahre"] in the frontend is not easy to understand for users 

;-)

**Comment by semohr** [comment]
The A00-A04 is kinda correct tho. This pandas dataframe you looked at is **not** for the new cases but for the population data. There is no other better data on it and also I feel like +1 year for the population data is a reasonable approximation.

In the worst case the increase for population would result in a smaller incidence for age group A00-A04. And decrease in the population for the age group A05-A15 would decrease the incidence slightly. On the other hand, overall population data is quite noisy and not updated very frequently so it should not make too big of a difference also there is no more accurate way to do it.
